apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  labels:
    app: myblog-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myblog-search
      name: middleware
  template:
    metadata:
      labels:
        app: myblog-search
        name: middleware
    spec:
      containers:
      - name: middleware
        image: sean1975/myblog-search:middleware
        envFrom:
        - configMapRef:
            name: myblog-search-env
        imagePullPolicy: Always
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: middleware
  labels:
    app: myblog-search
spec:
  type: ClusterIP
  selector:
    app: myblog-search
    name: middleware
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
