apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: myblog-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myblog-search
      name: nginx
  template:
    metadata:
      labels:
        app: myblog-search
        name: nginx
    spec:
      containers:
      - name: nginx
        image: sean1975/myblog-search:nginx-gke
        imagePullPolicy: Always
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    cloud.google.com/load-balancer-type: "External"
  labels:
    app: myblog-search
spec:
  type: LoadBalancer
  selector:
    app: myblog-search
    name: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
