apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa
  labels:
    app: vespa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vespa
      name: vespa
  serviceName: vespa
  template:
    metadata:
      labels:
        app: vespa
        name: vespa
    spec:
      containers:
      - name: vespa
        image: vespaengine/vespa
        imagePullPolicy: Always
        securityContext:
          privileged: true
