version: '3.9'
services:
  vespa:
    image: vespaengine/vespa
    container_name: myblog-search-vespa
    hostname: myblog-search-vespa
    ports:
      - 8080:8080
      - 19112:19112
      - 19071:19071
    volumes:
      - type: volume
        source: vespa-var
        target: /opt/vespa/var
      - type: volume
        source: vespa-logs
        target: /opt/vespa/logs
      - type: bind
        source: ./vespa/conf
        target: /opt/vespa/conf/jieba
      - type: bind
        source: ./vespa/application
        target: /application
        read_only: true
    deploy:
      resources:
        limits:
          memory: 6G
  middleware:
    image: sean1975/myblog-search:middleware
    container_name: myblog-search-middleware
    hostname: myblog-search-middleware
    ports:
      - 8000:80
    environment:
      - BACKEND_URL=http://host.docker.internal:8080
  nginx:
    image: nginx:1.21.0
    container_name: myblog-search-nginx
    hostname: myblog-search-nginx
    ports:
      - 80:80
    environment:
      - MIDDLEWARE_URL=http://host.docker.internal:8000
    volumes:
      - type: bind
        source: ./nginx/etc/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./nginx/etc/templates/default.conf.template
        target: /etc/nginx/templates/default.conf.template
        read_only: true
      - type: bind
        source: ./nginx/html
        target: /usr/share/nginx/html
        read_only: true
      - type: bind
        source: ./nginx/css
        target: /usr/share/nginx/css
        read_only: true
      - type: bind
        source: ./nginx/xslt
        target: /usr/share/nginx/xslt
        read_only: true
volumes:
  vespa-var:
    driver: local
  vespa-logs:
    driver: local
  crawler-backup:
    driver: local
