apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crawler-pvc
  namespace: default
  labels:
    app: myblog-search
spec:
  storageClassName: "standard-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
