apiVersion: batch/v1
kind: Job
metadata:
  name: crawler
spec:
  template:
    spec:
      containers:
      - name: crawler
        image: sean1975/myblog-search:crawler
        envFrom:
        - configMapRef:
            name: myblog-search-env
        imagePullPolicy: Always
      restartPolicy: Never
