apiVersion: v1
kind: Pod
metadata:
  name: crawler
  labels:
    app: myblog-search
spec:
  containers:
  - name: crawler
    image: sean1975/myblog-search:crawler
    imagePullPolicy: Always
    command: ['sleep', 'infinity']
    envFrom:
    - configMapRef:
          name: myblog-search-env
    volumeMounts:
    - name: crawler-volume
      mountPath: /crawler/backup
  volumes:
  - name: crawler-volume
    persistentVolumeClaim:
      claimName: crawler-pvc
