apiVersion: v1
kind: Service
metadata:
  name: vespa
  annotations:
    cloud.google.com/load-balancer-type: "External"
  labels:
    app: myblog-search
spec:
  type: LoadBalancer
  selector:
    app: myblog-search
    name: vespa
  ports:
  - name: container
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: config
    port: 19071
    targetPort: 19071
    protocol: TCP
