apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa
  labels:
    app: myblog-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myblog-search
      name: vespa
  serviceName: vespa
  template:
    metadata:
      labels:
        app: myblog-search
        name: vespa
    spec:
      containers:
      - name: vespa
        image: sean1975/myblog-search:vespa
        imagePullPolicy: Always
        securityContext:
          privileged: true
