apiVersion: v1
kind: Service
metadata:
  name: middleware
  annotations:
    cloud.google.com/load-balancer-type: "External"
  labels:
    app: myblog-search
spec:
  type: LoadBalancer
  selector:
    app: myblog-search
    name: middleware
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
