apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: middleware
  labels:
    app: myblog-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myblog-search
      name: middleware
  serviceName: middleware
  template:
    metadata:
      labels:
        app: myblog-search
        name: middleware
    spec:
      containers:
      - name: middleware
        image: sean1975/myblog-search:middleware
        env:
        - name: BACKEND_URL
          value: "http://vespa.default.svc.cluster.local:8080/search"
        imagePullPolicy: Always
        securityContext:
          privileged: true
