FROM nginx:1.21.0

COPY etc/nginx.conf /etc/nginx/nginx.conf
COPY etc/conf.d/google-kubernetes-engine.conf /etc/nginx/conf.d/default.conf
COPY html/index.html /usr/share/nginx/html/index.html
COPY xslt/result.xsl /usr/share/nginx/xslt/result.xsl
