apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: myblog-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myblog-search
      name: nginx
  template:
    metadata:
      labels:
        app: myblog-search
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: myblog-search-env
        securityContext:
          privileged: true
        volumeMounts:
        - name: nginx-conf-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-template-volume
          mountPath: /etc/nginx/templates
          readOnly: true
        - name: nginx-html-volume
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: nginx-css-volume
          mountPath: /usr/share/nginx/css
          readOnly: true
        - name: nginx-xslt-volume
          mountPath: /usr/share/nginx/xslt
          readOnly: true
      volumes:
      - name: nginx-conf-volume
        configMap:
          name: nginx-conf
      - name: nginx-template-volume
        configMap:
          name: nginx-template
      - name: nginx-html-volume
        configMap:
          name: nginx-html
      - name: nginx-css-volume
        configMap:
          name: nginx-css
      - name: nginx-xslt-volume
        configMap:
          name: nginx-xslt
