name: Docker Image Middleware CI

on:
  push:
    branches: [ master ]
    paths:
      - 'middleware/**'
      - '!middleware/*.yaml'

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd middleware ; docker build . --file Dockerfile --tag myblog-search:middleware
    - name: Login Docker Hub
      env:
        DOCKER_PASSWORD: $${secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Push the Docker image to Docker Hub
      run: docker push $DOCKER_USERNAME/myblog-search:middleware
      
