name: GKE Elastic CD

on:
  push:
    branches:
      - master
    paths:
      - 'elastic/*.yaml'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: taiwan-cluster
  GKE_ZONE: asia-east1-a

concurrency: elastic

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Deploy to the GKE cluster when elastic.yaml is changed
    - name: Deploy
      if: ${{ github.event_name == 'push' }}
      run: |-
        kubectl apply -f elastic/elastic.yaml
        kubectl rollout status statefulset/elastic
        kubectl get services/elastic -o wide

    # Otherwise restart pods on the GKE cluster to pull the latest docker image
    - name: Restart
      if: ${{ github.event_name != 'push' }}
      run: |-
        kubectl rollout restart statefulset/elastic
        kubectl rollout status statefulset/elastic
        kubectl get services/elastic -o wide
