name: GKE Middleware CD

on:
  push:
    branches:
      - master
    paths:
      - 'middleware/*.yaml'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: taiwan-cluster
  GKE_ZONE: asia-east1-a

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: middleware

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Deploy to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -f middleware/middleware.yaml
        kubectl rollout status deployment/middleware
        kubectl get services/middleware -o wide

    - name: Reload Nginx
      run: |-
        kubectl exec deployment/nginx -- nginx -s reload
